packages:
  # Core applications
  - 'give-care-app'                    # TypeScript/Convex backend
  - 'give-care-app/admin-frontend'    # Admin dashboard (Vite + React)
  - 'give-care-site'                   # Marketing website
  - 'give-care-story'                  # Presentation system
