#!/usr/bin/env node

/**
 * Setup Convex configuration for CI/CD builds
 *
 * Extracts deployment name from VITE_CONVEX_URL and creates .env.local
 * with proper CONVEX_DEPLOYMENT format for convex codegen.
 *
 * Usage: node scripts/setup-convex.js
 * Requires: VITE_CONVEX_URL environment variable
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get VITE_CONVEX_URL from environment
const convexUrl = process.env.VITE_CONVEX_URL;

if (!convexUrl) {
  console.error('❌ Error: VITE_CONVEX_URL environment variable is not set');
  console.error('Please configure VITE_CONVEX_URL in your Cloudflare Pages environment variables');
  process.exit(1);
}

try {
  // Extract deployment name from URL
  // Example: https://agreeable-lion-831.convex.cloud -> agreeable-lion-831
  const url = new URL(convexUrl);
  const deploymentName = url.hostname.split('.')[0];

  if (!deploymentName) {
    throw new Error('Could not extract deployment name from URL');
  }

  // Determine environment (prod vs dev)
  // Use "prod:" prefix for production deployments
  const environment = process.env.CF_PAGES_BRANCH === 'main' ? 'prod' : 'dev';
  const convexDeployment = `${environment}:${deploymentName}`;

  // Create .env.local content
  const envContent = `# Auto-generated by scripts/setup-convex.js
CONVEX_DEPLOYMENT=${convexDeployment}
VITE_CONVEX_URL=${convexUrl}
`;

  // Write .env.local file
  const envPath = join(__dirname, '..', '.env.local');
  writeFileSync(envPath, envContent, 'utf-8');

  console.log('✅ Created .env.local with:');
  console.log(`   CONVEX_DEPLOYMENT=${convexDeployment}`);
  console.log(`   VITE_CONVEX_URL=${convexUrl}`);
  console.log('');

  // Also create .env.local in give-care-app for codegen
  const appEnvPath = join(__dirname, '..', '..', 'give-care-app', '.env.local');
  writeFileSync(appEnvPath, envContent, 'utf-8');
  console.log('✅ Created give-care-app .env.local for codegen');
  console.log('');

  // Always attempt to regenerate Convex types to ensure they're up-to-date
  // This is important because new functions may have been added to the deployment
  const { existsSync } = await import('fs');
  const { execSync } = await import('child_process');
  const adminDir = join(__dirname, '..'); // give-care-admin
  const appDir = join(__dirname, '..', '..', 'give-care-app'); // give-care-app (sibling)
  const typesPath = join(appDir, 'convex', '_generated', 'api.d.ts');

  console.log('📦 Running convex codegen to ensure types are up-to-date...');
  try {
    execSync('npx convex codegen --typecheck disable', {
      cwd: appDir,
      stdio: 'inherit',
      env: { ...process.env, CONVEX_DEPLOYMENT: convexDeployment }
    });
    console.log('✅ Convex types generated successfully');
  } catch (codegenError) {
    if (existsSync(typesPath)) {
      console.warn('⚠️  Convex codegen failed, but types exist - using committed types');
      console.warn('   Note: Types may be stale. Ensure Convex deployment is up-to-date.');
    } else {
      console.error('❌ Convex codegen failed and no types found!');
      console.error('   Build will likely fail. Please ensure:');
      console.error('   1. Convex deployment is up-to-date');
      console.error('   2. CONVEX_DEPLOYMENT is correctly configured');
      console.error('   3. Network access to Convex is available');
      throw codegenError;
    }
  }

} catch (error) {
  console.error('❌ Error setting up Convex configuration:', error.message);
  process.exit(1);
}
