#!/usr/bin/env node

/**
 * Setup Convex configuration for CI/CD builds
 *
 * Extracts deployment name from VITE_CONVEX_URL and creates .env.local
 * with proper CONVEX_DEPLOYMENT format for convex codegen.
 *
 * Usage: node scripts/setup-convex.js
 * Requires: VITE_CONVEX_URL environment variable
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get VITE_CONVEX_URL from environment
const convexUrl = process.env.VITE_CONVEX_URL;

if (!convexUrl) {
  console.error('❌ Error: VITE_CONVEX_URL environment variable is not set');
  console.error('Please configure VITE_CONVEX_URL in your Cloudflare Pages environment variables');
  process.exit(1);
}

try {
  // Extract deployment name from URL
  // Example: https://agreeable-lion-831.convex.cloud -> agreeable-lion-831
  const url = new URL(convexUrl);
  const deploymentName = url.hostname.split('.')[0];

  if (!deploymentName) {
    throw new Error('Could not extract deployment name from URL');
  }

  // Determine environment (prod vs dev)
  // Use "prod:" prefix for production deployments
  const environment = process.env.CF_PAGES_BRANCH === 'main' ? 'prod' : 'dev';
  const convexDeployment = `${environment}:${deploymentName}`;

  // Create .env.local content
  const envContent = `# Auto-generated by scripts/setup-convex.js
CONVEX_DEPLOYMENT=${convexDeployment}
VITE_CONVEX_URL=${convexUrl}
`;

  // Write .env.local file
  const envPath = join(__dirname, '..', '.env.local');
  writeFileSync(envPath, envContent, 'utf-8');

  console.log('✅ Created .env.local with:');
  console.log(`   CONVEX_DEPLOYMENT=${convexDeployment}`);
  console.log(`   VITE_CONVEX_URL=${convexUrl}`);
  console.log('');

  // Also create parent .env.local for codegen
  const parentEnvPath = join(__dirname, '..', '..', '.env.local');
  writeFileSync(parentEnvPath, envContent, 'utf-8');
  console.log('✅ Created parent .env.local for codegen');
  console.log('');

  // Check if Convex types exist, run codegen only if needed/possible
  const { existsSync } = await import('fs');
  const { execSync } = await import('child_process');
  const adminDir = join(__dirname, '..'); // give-care-app/admin
  const appDir = join(adminDir, '..'); // give-care-app
  const typesPath = join(appDir, 'convex', '_generated', 'api.d.ts');

  if (existsSync(typesPath)) {
    console.log('✅ Convex types already exist, skipping codegen');
  } else {
    console.log('📦 Running convex codegen...');
    try {
      execSync('npx convex codegen --typecheck disable', {
        cwd: appDir,
        stdio: 'inherit',
        env: { ...process.env, CONVEX_DEPLOYMENT: convexDeployment }
      });
      console.log('✅ Convex types generated successfully');
    } catch (codegenError) {
      console.warn('⚠️  Convex codegen failed, but continuing build...');
      console.warn('   Using committed types from repository');
    }
  }

} catch (error) {
  console.error('❌ Error setting up Convex configuration:', error.message);
  process.exit(1);
}
